/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SaleorNtmsRouteImport } from './routes/saleor-ntms'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DefaultRouteRouteImport } from './routes/_default/route'
import { Route as CheckoutRouteRouteImport } from './routes/_checkout/route'
import { Route as AccountRouteRouteImport } from './routes/_account/route'
import { Route as DefaultIndexRouteImport } from './routes/_default/index'
import { Route as DefaultVerifyEmailAddressChangeRouteImport } from './routes/_default/verify-email-address-change'
import { Route as DefaultVerifyRouteImport } from './routes/_default/verify'
import { Route as DefaultUpdateEmailRouteImport } from './routes/_default/update-email'
import { Route as DefaultSignInRouteImport } from './routes/_default/sign-in'
import { Route as DefaultResetPasswordRouteImport } from './routes/_default/reset-password'
import { Route as DefaultResendVerificationRouteImport } from './routes/_default/resend-verification'
import { Route as DefaultRegisterRouteImport } from './routes/_default/register'
import { Route as DefaultPasswordResetRouteImport } from './routes/_default/password-reset'
import { Route as DefaultForgotPasswordRouteImport } from './routes/_default/forgot-password'
import { Route as DefaultSearchRouteRouteImport } from './routes/_default/_search/route'
import { Route as CheckoutCheckoutRouteRouteImport } from './routes/_checkout/checkout/route'
import { Route as AccountAccountIndexRouteImport } from './routes/_account/account/index'
import { Route as DefaultProductProductIdRouteImport } from './routes/_default/product/$productId'
import { Route as CheckoutCheckoutStepRouteImport } from './routes/_checkout/checkout/$step'
import { Route as AccountAccountSettingsRouteImport } from './routes/_account/account/settings'
import { Route as AccountAccountSecurityRouteImport } from './routes/_account/account/security'
import { Route as AccountAccountAddressesRouteImport } from './routes/_account/account/addresses'
import { Route as DefaultSearchSearchIndexRouteImport } from './routes/_default/_search/search/index'
import { Route as AccountAccountOrdersIndexRouteImport } from './routes/_account/account/orders/index'
import { Route as DefaultSearchCollectionsCollectionRouteImport } from './routes/_default/_search/collections/$collection'
import { Route as CheckoutCheckoutConfirmationCodeRouteImport } from './routes/_checkout/checkout/confirmation/$code'
import { Route as AccountAccountOrdersCodeRouteImport } from './routes/_account/account/orders/$code'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleorNtmsRoute = SaleorNtmsRouteImport.update({
  id: '/saleor-ntms',
  path: '/saleor-ntms',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultRouteRoute = DefaultRouteRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/_checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultVerifyEmailAddressChangeRoute =
  DefaultVerifyEmailAddressChangeRouteImport.update({
    id: '/verify-email-address-change',
    path: '/verify-email-address-change',
    getParentRoute: () => DefaultRouteRoute,
  } as any)
const DefaultVerifyRoute = DefaultVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultUpdateEmailRoute = DefaultUpdateEmailRouteImport.update({
  id: '/update-email',
  path: '/update-email',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultSignInRoute = DefaultSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultResetPasswordRoute = DefaultResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultResendVerificationRoute =
  DefaultResendVerificationRouteImport.update({
    id: '/resend-verification',
    path: '/resend-verification',
    getParentRoute: () => DefaultRouteRoute,
  } as any)
const DefaultRegisterRoute = DefaultRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultPasswordResetRoute = DefaultPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultForgotPasswordRoute = DefaultForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultSearchRouteRoute = DefaultSearchRouteRouteImport.update({
  id: '/_search',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const CheckoutCheckoutRouteRoute = CheckoutCheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const AccountAccountIndexRoute = AccountAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DefaultProductProductIdRoute = DefaultProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const CheckoutCheckoutStepRoute = CheckoutCheckoutStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => CheckoutCheckoutRouteRoute,
} as any)
const AccountAccountSettingsRoute = AccountAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAccountSecurityRoute = AccountAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAccountAddressesRoute = AccountAccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DefaultSearchSearchIndexRoute =
  DefaultSearchSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => DefaultSearchRouteRoute,
  } as any)
const AccountAccountOrdersIndexRoute =
  AccountAccountOrdersIndexRouteImport.update({
    id: '/account/orders/',
    path: '/account/orders/',
    getParentRoute: () => AccountRouteRoute,
  } as any)
const DefaultSearchCollectionsCollectionRoute =
  DefaultSearchCollectionsCollectionRouteImport.update({
    id: '/collections/$collection',
    path: '/collections/$collection',
    getParentRoute: () => DefaultSearchRouteRoute,
  } as any)
const CheckoutCheckoutConfirmationCodeRoute =
  CheckoutCheckoutConfirmationCodeRouteImport.update({
    id: '/confirmation/$code',
    path: '/confirmation/$code',
    getParentRoute: () => CheckoutCheckoutRouteRoute,
  } as any)
const AccountAccountOrdersCodeRoute =
  AccountAccountOrdersCodeRouteImport.update({
    id: '/account/orders/$code',
    path: '/account/orders/$code',
    getParentRoute: () => AccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute
  '/healthz': typeof HealthzRoute
  '/logout': typeof LogoutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saleor-ntms': typeof SaleorNtmsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout': typeof CheckoutCheckoutRouteRouteWithChildren
  '/forgot-password': typeof DefaultForgotPasswordRoute
  '/password-reset': typeof DefaultPasswordResetRoute
  '/register': typeof DefaultRegisterRoute
  '/resend-verification': typeof DefaultResendVerificationRoute
  '/reset-password': typeof DefaultResetPasswordRoute
  '/sign-in': typeof DefaultSignInRoute
  '/update-email': typeof DefaultUpdateEmailRoute
  '/verify': typeof DefaultVerifyRoute
  '/verify-email-address-change': typeof DefaultVerifyEmailAddressChangeRoute
  '/account/addresses': typeof AccountAccountAddressesRoute
  '/account/security': typeof AccountAccountSecurityRoute
  '/account/settings': typeof AccountAccountSettingsRoute
  '/checkout/$step': typeof CheckoutCheckoutStepRoute
  '/product/$productId': typeof DefaultProductProductIdRoute
  '/account/': typeof AccountAccountIndexRoute
  '/account/orders/$code': typeof AccountAccountOrdersCodeRoute
  '/checkout/confirmation/$code': typeof CheckoutCheckoutConfirmationCodeRoute
  '/collections/$collection': typeof DefaultSearchCollectionsCollectionRoute
  '/account/orders/': typeof AccountAccountOrdersIndexRoute
  '/search/': typeof DefaultSearchSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultIndexRoute
  '/healthz': typeof HealthzRoute
  '/logout': typeof LogoutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saleor-ntms': typeof SaleorNtmsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout': typeof CheckoutCheckoutRouteRouteWithChildren
  '/forgot-password': typeof DefaultForgotPasswordRoute
  '/password-reset': typeof DefaultPasswordResetRoute
  '/register': typeof DefaultRegisterRoute
  '/resend-verification': typeof DefaultResendVerificationRoute
  '/reset-password': typeof DefaultResetPasswordRoute
  '/sign-in': typeof DefaultSignInRoute
  '/update-email': typeof DefaultUpdateEmailRoute
  '/verify': typeof DefaultVerifyRoute
  '/verify-email-address-change': typeof DefaultVerifyEmailAddressChangeRoute
  '/account/addresses': typeof AccountAccountAddressesRoute
  '/account/security': typeof AccountAccountSecurityRoute
  '/account/settings': typeof AccountAccountSettingsRoute
  '/checkout/$step': typeof CheckoutCheckoutStepRoute
  '/product/$productId': typeof DefaultProductProductIdRoute
  '/account': typeof AccountAccountIndexRoute
  '/account/orders/$code': typeof AccountAccountOrdersCodeRoute
  '/checkout/confirmation/$code': typeof CheckoutCheckoutConfirmationCodeRoute
  '/collections/$collection': typeof DefaultSearchCollectionsCollectionRoute
  '/account/orders': typeof AccountAccountOrdersIndexRoute
  '/search': typeof DefaultSearchSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteRouteWithChildren
  '/_checkout': typeof CheckoutRouteRouteWithChildren
  '/_default': typeof DefaultRouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/logout': typeof LogoutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saleor-ntms': typeof SaleorNtmsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_checkout/checkout': typeof CheckoutCheckoutRouteRouteWithChildren
  '/_default/_search': typeof DefaultSearchRouteRouteWithChildren
  '/_default/forgot-password': typeof DefaultForgotPasswordRoute
  '/_default/password-reset': typeof DefaultPasswordResetRoute
  '/_default/register': typeof DefaultRegisterRoute
  '/_default/resend-verification': typeof DefaultResendVerificationRoute
  '/_default/reset-password': typeof DefaultResetPasswordRoute
  '/_default/sign-in': typeof DefaultSignInRoute
  '/_default/update-email': typeof DefaultUpdateEmailRoute
  '/_default/verify': typeof DefaultVerifyRoute
  '/_default/verify-email-address-change': typeof DefaultVerifyEmailAddressChangeRoute
  '/_default/': typeof DefaultIndexRoute
  '/_account/account/addresses': typeof AccountAccountAddressesRoute
  '/_account/account/security': typeof AccountAccountSecurityRoute
  '/_account/account/settings': typeof AccountAccountSettingsRoute
  '/_checkout/checkout/$step': typeof CheckoutCheckoutStepRoute
  '/_default/product/$productId': typeof DefaultProductProductIdRoute
  '/_account/account/': typeof AccountAccountIndexRoute
  '/_account/account/orders/$code': typeof AccountAccountOrdersCodeRoute
  '/_checkout/checkout/confirmation/$code': typeof CheckoutCheckoutConfirmationCodeRoute
  '/_default/_search/collections/$collection': typeof DefaultSearchCollectionsCollectionRoute
  '/_account/account/orders/': typeof AccountAccountOrdersIndexRoute
  '/_default/_search/search/': typeof DefaultSearchSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/logout'
    | '/robots.txt'
    | '/saleor-ntms'
    | '/sitemap.xml'
    | '/checkout'
    | '/forgot-password'
    | '/password-reset'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/sign-in'
    | '/update-email'
    | '/verify'
    | '/verify-email-address-change'
    | '/account/addresses'
    | '/account/security'
    | '/account/settings'
    | '/checkout/$step'
    | '/product/$productId'
    | '/account/'
    | '/account/orders/$code'
    | '/checkout/confirmation/$code'
    | '/collections/$collection'
    | '/account/orders/'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/logout'
    | '/robots.txt'
    | '/saleor-ntms'
    | '/sitemap.xml'
    | '/checkout'
    | '/forgot-password'
    | '/password-reset'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/sign-in'
    | '/update-email'
    | '/verify'
    | '/verify-email-address-change'
    | '/account/addresses'
    | '/account/security'
    | '/account/settings'
    | '/checkout/$step'
    | '/product/$productId'
    | '/account'
    | '/account/orders/$code'
    | '/checkout/confirmation/$code'
    | '/collections/$collection'
    | '/account/orders'
    | '/search'
  id:
    | '__root__'
    | '/_account'
    | '/_checkout'
    | '/_default'
    | '/healthz'
    | '/logout'
    | '/robots.txt'
    | '/saleor-ntms'
    | '/sitemap.xml'
    | '/_checkout/checkout'
    | '/_default/_search'
    | '/_default/forgot-password'
    | '/_default/password-reset'
    | '/_default/register'
    | '/_default/resend-verification'
    | '/_default/reset-password'
    | '/_default/sign-in'
    | '/_default/update-email'
    | '/_default/verify'
    | '/_default/verify-email-address-change'
    | '/_default/'
    | '/_account/account/addresses'
    | '/_account/account/security'
    | '/_account/account/settings'
    | '/_checkout/checkout/$step'
    | '/_default/product/$productId'
    | '/_account/account/'
    | '/_account/account/orders/$code'
    | '/_checkout/checkout/confirmation/$code'
    | '/_default/_search/collections/$collection'
    | '/_account/account/orders/'
    | '/_default/_search/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  DefaultRouteRoute: typeof DefaultRouteRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LogoutRoute: typeof LogoutRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SaleorNtmsRoute: typeof SaleorNtmsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saleor-ntms': {
      id: '/saleor-ntms'
      path: '/saleor-ntms'
      fullPath: '/saleor-ntms'
      preLoaderRoute: typeof SaleorNtmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_checkout': {
      id: '/_checkout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/verify-email-address-change': {
      id: '/_default/verify-email-address-change'
      path: '/verify-email-address-change'
      fullPath: '/verify-email-address-change'
      preLoaderRoute: typeof DefaultVerifyEmailAddressChangeRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/verify': {
      id: '/_default/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof DefaultVerifyRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/update-email': {
      id: '/_default/update-email'
      path: '/update-email'
      fullPath: '/update-email'
      preLoaderRoute: typeof DefaultUpdateEmailRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/sign-in': {
      id: '/_default/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof DefaultSignInRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/reset-password': {
      id: '/_default/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof DefaultResetPasswordRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/resend-verification': {
      id: '/_default/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof DefaultResendVerificationRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/register': {
      id: '/_default/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof DefaultRegisterRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/password-reset': {
      id: '/_default/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof DefaultPasswordResetRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/forgot-password': {
      id: '/_default/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof DefaultForgotPasswordRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/_search': {
      id: '/_default/_search'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultSearchRouteRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_checkout/checkout': {
      id: '/_checkout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutCheckoutRouteRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/_account/account/': {
      id: '/_account/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountAccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_default/product/$productId': {
      id: '/_default/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof DefaultProductProductIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_checkout/checkout/$step': {
      id: '/_checkout/checkout/$step'
      path: '/$step'
      fullPath: '/checkout/$step'
      preLoaderRoute: typeof CheckoutCheckoutStepRouteImport
      parentRoute: typeof CheckoutCheckoutRouteRoute
    }
    '/_account/account/settings': {
      id: '/_account/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountAccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account/security': {
      id: '/_account/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountAccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account/addresses': {
      id: '/_account/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAccountAddressesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_default/_search/search/': {
      id: '/_default/_search/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof DefaultSearchSearchIndexRouteImport
      parentRoute: typeof DefaultSearchRouteRoute
    }
    '/_account/account/orders/': {
      id: '/_account/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountAccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_default/_search/collections/$collection': {
      id: '/_default/_search/collections/$collection'
      path: '/collections/$collection'
      fullPath: '/collections/$collection'
      preLoaderRoute: typeof DefaultSearchCollectionsCollectionRouteImport
      parentRoute: typeof DefaultSearchRouteRoute
    }
    '/_checkout/checkout/confirmation/$code': {
      id: '/_checkout/checkout/confirmation/$code'
      path: '/confirmation/$code'
      fullPath: '/checkout/confirmation/$code'
      preLoaderRoute: typeof CheckoutCheckoutConfirmationCodeRouteImport
      parentRoute: typeof CheckoutCheckoutRouteRoute
    }
    '/_account/account/orders/$code': {
      id: '/_account/account/orders/$code'
      path: '/account/orders/$code'
      fullPath: '/account/orders/$code'
      preLoaderRoute: typeof AccountAccountOrdersCodeRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAccountAddressesRoute: typeof AccountAccountAddressesRoute
  AccountAccountSecurityRoute: typeof AccountAccountSecurityRoute
  AccountAccountSettingsRoute: typeof AccountAccountSettingsRoute
  AccountAccountIndexRoute: typeof AccountAccountIndexRoute
  AccountAccountOrdersCodeRoute: typeof AccountAccountOrdersCodeRoute
  AccountAccountOrdersIndexRoute: typeof AccountAccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAccountAddressesRoute: AccountAccountAddressesRoute,
  AccountAccountSecurityRoute: AccountAccountSecurityRoute,
  AccountAccountSettingsRoute: AccountAccountSettingsRoute,
  AccountAccountIndexRoute: AccountAccountIndexRoute,
  AccountAccountOrdersCodeRoute: AccountAccountOrdersCodeRoute,
  AccountAccountOrdersIndexRoute: AccountAccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface CheckoutCheckoutRouteRouteChildren {
  CheckoutCheckoutStepRoute: typeof CheckoutCheckoutStepRoute
  CheckoutCheckoutConfirmationCodeRoute: typeof CheckoutCheckoutConfirmationCodeRoute
}

const CheckoutCheckoutRouteRouteChildren: CheckoutCheckoutRouteRouteChildren = {
  CheckoutCheckoutStepRoute: CheckoutCheckoutStepRoute,
  CheckoutCheckoutConfirmationCodeRoute: CheckoutCheckoutConfirmationCodeRoute,
}

const CheckoutCheckoutRouteRouteWithChildren =
  CheckoutCheckoutRouteRoute._addFileChildren(
    CheckoutCheckoutRouteRouteChildren,
  )

interface CheckoutRouteRouteChildren {
  CheckoutCheckoutRouteRoute: typeof CheckoutCheckoutRouteRouteWithChildren
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutCheckoutRouteRoute: CheckoutCheckoutRouteRouteWithChildren,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface DefaultSearchRouteRouteChildren {
  DefaultSearchCollectionsCollectionRoute: typeof DefaultSearchCollectionsCollectionRoute
  DefaultSearchSearchIndexRoute: typeof DefaultSearchSearchIndexRoute
}

const DefaultSearchRouteRouteChildren: DefaultSearchRouteRouteChildren = {
  DefaultSearchCollectionsCollectionRoute:
    DefaultSearchCollectionsCollectionRoute,
  DefaultSearchSearchIndexRoute: DefaultSearchSearchIndexRoute,
}

const DefaultSearchRouteRouteWithChildren =
  DefaultSearchRouteRoute._addFileChildren(DefaultSearchRouteRouteChildren)

interface DefaultRouteRouteChildren {
  DefaultSearchRouteRoute: typeof DefaultSearchRouteRouteWithChildren
  DefaultForgotPasswordRoute: typeof DefaultForgotPasswordRoute
  DefaultPasswordResetRoute: typeof DefaultPasswordResetRoute
  DefaultRegisterRoute: typeof DefaultRegisterRoute
  DefaultResendVerificationRoute: typeof DefaultResendVerificationRoute
  DefaultResetPasswordRoute: typeof DefaultResetPasswordRoute
  DefaultSignInRoute: typeof DefaultSignInRoute
  DefaultUpdateEmailRoute: typeof DefaultUpdateEmailRoute
  DefaultVerifyRoute: typeof DefaultVerifyRoute
  DefaultVerifyEmailAddressChangeRoute: typeof DefaultVerifyEmailAddressChangeRoute
  DefaultIndexRoute: typeof DefaultIndexRoute
  DefaultProductProductIdRoute: typeof DefaultProductProductIdRoute
}

const DefaultRouteRouteChildren: DefaultRouteRouteChildren = {
  DefaultSearchRouteRoute: DefaultSearchRouteRouteWithChildren,
  DefaultForgotPasswordRoute: DefaultForgotPasswordRoute,
  DefaultPasswordResetRoute: DefaultPasswordResetRoute,
  DefaultRegisterRoute: DefaultRegisterRoute,
  DefaultResendVerificationRoute: DefaultResendVerificationRoute,
  DefaultResetPasswordRoute: DefaultResetPasswordRoute,
  DefaultSignInRoute: DefaultSignInRoute,
  DefaultUpdateEmailRoute: DefaultUpdateEmailRoute,
  DefaultVerifyRoute: DefaultVerifyRoute,
  DefaultVerifyEmailAddressChangeRoute: DefaultVerifyEmailAddressChangeRoute,
  DefaultIndexRoute: DefaultIndexRoute,
  DefaultProductProductIdRoute: DefaultProductProductIdRoute,
}

const DefaultRouteRouteWithChildren = DefaultRouteRoute._addFileChildren(
  DefaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountRouteRoute: AccountRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  DefaultRouteRoute: DefaultRouteRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LogoutRoute: LogoutRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SaleorNtmsRoute: SaleorNtmsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
